from __future__ import annotations

import html
from datetime import UTC, datetime, timedelta

from feedgen.feed import FeedGenerator

from .config import settings
from .models import Book, Chapter, ChapterStatus


def build_book_feed(book: Book, chapters: list[Chapter]) -> bytes:
    """Build an iTunes-compatible podcast RSS feed for a single book.

    Audiobook-critical settings:
    - itunes:type=serial (oldest-first playback)
    - season=1 with monotonic episode numbers
    - 1400x1400 cover via book.cover_path (already sized in pipeline)
    Only completed chapters are listed as episodes.
    """
    fg = FeedGenerator()
    fg.load_extension("podcast")

    base = settings.base_url.rstrip("/")
    feed_url = f"{base}/feed/{book.feed_token}"
    cover_url = f"{base}/cover/{book.feed_token}.jpg"

    fg.title(book.title)
    fg.author({"name": book.author or "Bookcast"})
    fg.link(href=feed_url, rel="self")
    fg.link(href=base, rel="alternate")
    fg.language(book.language or "en")
    fg.description(_description(book))
    fg.image(cover_url)
    fg.pubDate(_to_pubdate(book.created_at))
    fg.lastBuildDate(_now())

    pe = fg.podcast
    pe.itunes_type("serial")
    pe.itunes_author(book.author or "Bookcast")
    pe.itunes_summary(_description(book))
    pe.itunes_explicit("no")
    pe.itunes_category("Arts", "Books")
    pe.itunes_image(cover_url)
    pe.itunes_block(True)  # don't list our private feed in Apple's directory

    # Episode numbers reflect position among *non-skipped* chapters (1-based).
    # Skipped chapters don't consume episode slots, so the user sees a clean
    # 1, 2, 3, … sequence even after skipping front/back-matter.
    listed_chapters = sorted(
        (c for c in chapters if c.status != ChapterStatus.skipped),
        key=lambda c: c.idx,
    )
    episode_no_by_chapter_id = {c.id: i for i, c in enumerate(listed_chapters, start=1)}

    done_chapters = [c for c in chapters if c.status == ChapterStatus.done and c.mp3_path]
    base_time = book.created_at or datetime.now(UTC)
    if base_time.tzinfo is None:
        base_time = base_time.replace(tzinfo=UTC)

    for ch in done_chapters:
        fe = fg.add_entry()
        ep_url = f"{base}/audio/{ch.id}.mp3?t={book.feed_token}"
        guid = f"{book.feed_token}-{ch.id}"
        episode_no = episode_no_by_chapter_id.get(ch.id, ch.idx)
        fe.id(guid)
        fe.guid(guid, permalink=False)
        fe.title(ch.title or f"Chapter {ch.idx}")
        notes_text = _chapter_shownotes(ch)
        notes_html = _chapter_shownotes_html(ch)
        fe.description(notes_text)
        fe.content(notes_html, type="CDATA")
        # Stagger pubDate so order is preserved (RSS readers sort by date).
        fe.pubDate(_to_pubdate(base_time + timedelta(minutes=episode_no)))
        fe.enclosure(ep_url, str(ch.bytes_size or 0), "audio/mpeg")
        fe.podcast.itunes_episode(episode_no)
        fe.podcast.itunes_season(1)
        fe.podcast.itunes_episode_type("full")
        fe.podcast.itunes_image(cover_url)
        if ch.duration_s:
            fe.podcast.itunes_duration(_format_duration(ch.duration_s))

    return fg.rss_str(pretty=True)


def _description(book: Book) -> str:
    bits = [f"{book.title}"]
    if book.author:
        bits.append(f"by {book.author}")
    bits.append("Generated by Bookcast.")
    return " — ".join(bits)


def _chapter_shownotes(chapter: Chapter) -> str:
    title = chapter.title or f"Chapter {chapter.idx}"
    text = (chapter.text or "").strip()
    if not text:
        return title
    return f"{title}\n\n{text}"


def _chapter_shownotes_html(chapter: Chapter) -> str:
    title = html.escape(chapter.title or f"Chapter {chapter.idx}")
    text = html.escape((chapter.text or "").strip())
    if not text:
        return f"<h2>{title}</h2>"
    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    body = "\n".join(f"<p>{p}</p>" for p in paragraphs)
    return f"<h2>{title}</h2>\n{body}"


def _now() -> datetime:
    return datetime.now(UTC)


def _to_pubdate(dt: datetime) -> datetime:
    if dt.tzinfo is None:
        return dt.replace(tzinfo=UTC)
    return dt


def _format_duration(seconds: int) -> str:
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}:{m:02d}:{s:02d}"
    return f"{m}:{s:02d}"
