from __future__ import annotations

from datetime import UTC, datetime, timedelta

from feedgen.feed import FeedGenerator

from .config import settings
from .models import Book, Chapter, ChapterStatus


def build_book_feed(book: Book, chapters: list[Chapter]) -> bytes:
    """Build an iTunes-compatible podcast RSS feed for a single book.

    Audiobook-critical settings:
    - itunes:type=serial (oldest-first playback)
    - season=1 with monotonic episode numbers
    - 1400x1400 cover via book.cover_path (already sized in pipeline)
    Only completed chapters are listed as episodes.
    """
    fg = FeedGenerator()
    fg.load_extension("podcast")

    base = settings.base_url.rstrip("/")
    feed_url = f"{base}/feed/{book.feed_token}"
    cover_url = f"{base}/cover/{book.feed_token}.jpg"

    fg.title(book.title)
    fg.author({"name": book.author or "Bookcast"})
    fg.link(href=feed_url, rel="self")
    fg.link(href=base, rel="alternate")
    fg.language(book.language or "en")
    fg.description(_description(book))
    fg.image(cover_url)
    fg.pubDate(_to_pubdate(book.created_at))
    fg.lastBuildDate(_now())

    pe = fg.podcast
    pe.itunes_type("serial")
    pe.itunes_author(book.author or "Bookcast")
    pe.itunes_summary(_description(book))
    pe.itunes_explicit("no")
    pe.itunes_category("Arts", "Books")
    pe.itunes_image(cover_url)
    pe.itunes_block(True)  # don't list our private feed in Apple's directory

    done_chapters = [c for c in chapters if c.status == ChapterStatus.done and c.mp3_path]
    base_time = book.created_at or datetime.now(UTC)
    if base_time.tzinfo is None:
        base_time = base_time.replace(tzinfo=UTC)

    for ch in done_chapters:
        fe = fg.add_entry()
        ep_url = f"{base}/audio/{ch.id}.mp3?t={book.feed_token}"
        guid = f"{book.feed_token}-{ch.id}"
        fe.id(guid)
        fe.guid(guid, permalink=False)
        fe.title(ch.title or f"Chapter {ch.idx}")
        fe.description(ch.title or f"Chapter {ch.idx}")
        # Stagger pubDate so order is preserved (RSS readers sort by date).
        fe.pubDate(_to_pubdate(base_time + timedelta(minutes=ch.idx)))
        fe.enclosure(ep_url, str(ch.bytes_size or 0), "audio/mpeg")
        fe.podcast.itunes_episode(ch.idx)
        fe.podcast.itunes_season(1)
        fe.podcast.itunes_episode_type("full")
        fe.podcast.itunes_image(cover_url)
        if ch.duration_s:
            fe.podcast.itunes_duration(_format_duration(ch.duration_s))

    return fg.rss_str(pretty=True)


def _description(book: Book) -> str:
    bits = [f"{book.title}"]
    if book.author:
        bits.append(f"by {book.author}")
    bits.append("Generated by Bookcast.")
    return " — ".join(bits)


def _now() -> datetime:
    return datetime.now(UTC)


def _to_pubdate(dt: datetime) -> datetime:
    if dt.tzinfo is None:
        return dt.replace(tzinfo=UTC)
    return dt


def _format_duration(seconds: int) -> str:
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}:{m:02d}:{s:02d}"
    return f"{m}:{s:02d}"
